#!/bin/sh

# Click aliases
AC='%{A:'           # start click area
AB=':}'             # end click area cmd
AE='%{A}'           # end click area

# Colors
W="%{F#FFFFFF}"
R="%{F#de0408}"
P="%{F#9500e6}"

# Define the clock
Clock() {
        date="$(date +'%T %a %b %d, %Y')"

        echo "${W}$date"
}

Spotify() {
	status="$(playerctl status)"
	if [ -z $status ]; then
		echo "${W}Vai ficar tudo bem"
	else
		artist="$(playerctl metadata artist)"
		title="$(playerctl metadata title)"
		echo "${R}$status: ${W}$artist - $title"
	fi

}

Workspace() {
	count="$(bspc query -D | wc -l)"	
	focused="$(bspc query -D -d focused --names)"

	echo "${W}[$focused - $count]"
}

# Install sysstat package
Cpu() {
	usage=$(mpstat 2 1 | awk 'END{print 100-$NF}' | sed 's/\.[^[:blank:]]*//')
	temp="$(sensors | grep "Core" | awk '{print $3}')"
	echo "${R}Cpu: ${W}$usage% ${P}- ${W}${temp}"
}

Weather() {
	temp="$(curl 'wttr.in/Sao_Paulo?format=3' | awk '{print $3}')"

	echo "${R}${temp}"
}

Drive() {
	avail="$(df -H | grep 'sda2' | awk '{print $4}')"
	used="$(df -H | grep 'sda2' | awk '{print $3}')"
	rootAvail="$(df -H | grep 'sda1' | awk '{print $4}')"
	rootUsed="$(df -H | grep 'sda1' | awk '{print $3}')"

	echo "${R}Hentai${W} Folder: ${P}[${W}$avail${P}:${W}$used${P}] [${W}$rootAvail${P}:${W}$rootUsed${P}]"
}

Mem() {
	formatMem=$(free -h | grep "Mem" | awk '{print $2":-:"$3}')
	echo "${R}Mem: ${P}[${W}$formatMem${P}]"
}

ResetKey() {
	echo "%{A:notify-send 'Opening terminal' && xfce4-terminal &:}${W}K%{A}"
}

while true; do
	echo "%{l} $(Workspace) $P| $(Spotify) %{r} $(ResetKey) ${P}| $(Mem) ${P}| $(Drive) ${P}| [$(Cpu):$(Weather)${P}] $P| $(Clock)"
        sleep 3
done
