#!/bin/bash

set -e
set -u

DATE="$(date +'%D %A %T')"
TARGET="#"
REPL="🞄"
FRED="\033[31m" # foreground red
RS="\033[0m"    # reset color

set +u

# Check if is empty
if [[ -z $1 ]]; then
    printf "${FRED}ERROR: ${RS}File was not provided\n" >&2
    exit 1
fi

# Check if is a invalid file
if ! [[ -f $1 ]]; then
    printf "${FRED}ERROR: ${RS}\`%s\` File provided is not a valid text file\n" "$INPUT" >&2
    exit 1
fi

OUTPUT=$(cat $1 | grep "$TARGET" | sed "s/#/$REPL/g")

# Need this variables to send notify-send through cron job
DISPLAY=:0 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus notify-send -t 20000 "$DATE" "$OUTPUT"

set -u
