#!/usr/bin/bash

FRED="\033[31m" # foreground red
RS="\033[0m"    # reset color

if [[ -z "$1" ]]; then
	notify-send -t 20000 "OwO" "<b><span color=\"red\">ERROR:</span></b>Text language was not provided."
	printf "${FRED}ERROR: ${RS}Text language was not provided.\n" >&2
	exit 1
fi

if [[ -z "$2" ]]; then
	notify-send -t 20000 "OwO" "<b><span color=\"red\">ERROR:</span></b>Target language was not provided."
	printf "${FRED}ERROR: ${RS}Target language was not provided.\n" >&2
	exit 1
fi

TEXT="$(xsel -o)"
TEXTLANG="$1"
TARGETLANG="$2"
TRANSLATION="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=$TEXTLANG&tl=$TARGETLANG&dt=t&q=$(echo $TEXT | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}' | sed -r 's/\s+\S+$//g')"
notify-send "OwO" "$TRANSLATION"
